hours/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shifts.urls')),
]

shifts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login$', views.login_handler),
    url(r'^logout$', views.logout_handler),
    url(r'^shifts$', views.shifts),
    url(r'^export$', views.export),
    url(r'^profile$', views.profile),
    url(r'^register$', views.register),
    url(r'^send_registration$', views.send_registration),
]

shifts/models.py
from django.db import models
from django.db import DataError 
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    auto_clock_out = models.TimeField(null=True, blank=True)

def profile_create_callback(sender, **kwargs):
    if kwargs['created'] == True:
        Profile(user = kwargs['instance']).save() 

post_save.connect(profile_create_callback, sender = User, weak = False)

class Event(models.Model):
    REQUIRED_EVENT = {
        'OUT': ('IN'),
        None: ('IN'),
        'IN': ('OUT','BST'),
        'BEN': ('OUT','BST'),
        'BST': ('BEN'),
    }
    EVENTS = (
        ('IN' ,'Clock in'),
        ('OUT','Clock out'),
        ('BST','Break start'),
        ('BEN','Break end'),
    )
    time = models.DateTimeField()
    event = models.CharField(max_length = 3, choices=EVENTS)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    @staticmethod
    def last_event(user):
        return Event.objects.filter(user = user).order_by('time').last()
        
    def save(self, *args, **kwargs):
        try:
            if(settings.DISABLE_CLOCK_CHECK == True ):
                super(Event, self).save(*args, **kwargs)
        except:
            pass
        last_event = self.last_event(self.user)
        if last_event != None:
            last_event = last_event.event
        if self.id == None and not self.event in self.REQUIRED_EVENT[last_event]:
            raise DataError('To "%s" you must "%s" first and not "%s"' % (self.event, self.REQUIRED_EVENT[last_event], last_event))

        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return "%d %s: %s @%s"%(self.id, self.user.username, self.event, self.time.strftime("%x %X"))

class Shift(models.Model):
    class Meta:
        permissions = (('can_view_others','Can veiw others shifts and events'),)

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    start = models.ForeignKey(Event, related_name = "start",on_delete = models.CASCADE)
    end = models.ForeignKey(Event, related_name = "end", on_delete = models.SET_NULL, null = True)
    tasks_completed = models.TextField()

class Registration(models.Model):
    class Meta:
        permissions = (('can_send_registration','Can send a registration request.'),)
    email = models.TextField()
    key_hash = models.BinaryField()

shifts/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from django.http import HttpResponseRedirect 
#from django.template import loader
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from shifts.models import Shift, Event, Profile, Registration
import bleach
import datetime
from django.utils import timezone
import hashlib
import random
import os
from django.core.mail import send_mail, send_mass_mail
import base64

def index(request):
    context = dict()
    if request.user.is_authenticated():
        messages.warning(request,"You are already signed in.")
        return HttpResponseRedirect("/shifts")
    return render(request, 'login.html', context)

@require_http_methods(['POST'])
def login_handler(request):
    username = request.POST['username'] 
    password = request.POST['password']
    user = authenticate(username=username,password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect("/shifts")
    else:
        messages.error(request, "Incorrect password.")
        return HttpResponseRedirect("/") 

@login_required 
def logout_handler(request):
    logout(request)
    messages.info(request, "You've been logout")
    return HttpResponseRedirect("/")

@login_required 
def shifts(request):
    last_shift = Shift.objects.filter(user = request.user).last()
    last_event = Event.objects.filter(user = request.user).last()

    if request.method == 'POST':
        event = request.POST.get("event")
        if event == "task" and last_shift != None:
            tasks = last_shift.tasks_completed
            task = bleach.clean(request.POST['desc']).replace('`','\'')
            if tasks == "":
                last_shift.tasks_completed = '`%s`' % task
            else:
                last_shift.tasks_completed = '%s,`%s`' % (tasks, task)
            last_shift.save()
        elif event in Event.REQUIRED_EVENT.keys():
            last_event = Event(time = timezone.now(), event = event, user = request.user)
            last_event.save()
            if event == "IN":
                last_shift = Shift(user = request.user, start = last_event, tasks_completed = "")
            elif event == "OUT":
                last_shift.end = last_event
            last_shift.save()
             
    context = {
        "last_shift": last_shift,
        "last_event": last_event,
        "lastest_events": Event.objects.filter(user = request.user),
        "event_choices": Event.EVENTS,
        "possible_events": Event.REQUIRED_EVENT[last_event.event if last_event != None else None]
    }
    if last_shift != None:
        context['tasks_completed'] = last_shift.tasks_completed[1:-1].split('`,`')

    return render(request, 'shifts.html', context)

@login_required
def export(request):
    daily_hours = []
    
    now_iso = timezone.now().isocalendar()
    total_hours = 0 


    year = int(request.GET.get("year", now_iso[0]))
    week = int(request.GET.get("week", now_iso[1]))
    
    context = {
       "year": year,
       "week": week
    }

    days_of_week = __get_days_in_week(year, week)

    user = request.user

    if request.user.has_perm('shifts.can_view_others'):
        try:
            user = User.objects.get(id = request.GET.get("user"))
        except ObjectDoesNotExist:
            pass

        context['view_user'] = user
        context['users'] = User.objects.all()

    day_shifts_and_hours = []

    for day in days_of_week:
        day_end = day + datetime.timedelta(days=1)
        shifts = Shift.objects.filter(user = user, start__time__gte = day, start__time__lt = day_end)
        hours = __calculate_hours(shifts)

        if hours == None:
            hours = 0
        else:
            hours = hours.total_seconds()/3600
            total_hours = total_hours + hours

        day_shifts_and_hours.append([day, shifts, hours])
    
    
    context['day_shifts_and_hours'] = day_shifts_and_hours
    context['total_hours'] = total_hours
    context['last_week'] = (day_shifts_and_hours[0][0] - datetime.timedelta(weeks=1)).isocalendar()
    context['next_week'] = (day_shifts_and_hours[0][0] + datetime.timedelta(weeks=1)).isocalendar()
    if request.GET.get("type") == "csv":
        return render(request, 'export.csv', context, content_type="text/csv")
    return render(request, "export.html", context)

def __calculate_hours(shifts):
    '''Returns timedelta of how much time worked..'''

    if shifts == None:
        return 0

    if type(shifts) == Shift:
        shifts = [shifts]

    time = datetime.timedelta(0)
    for shift in shifts:
        if shift.end != None:
            time += shift.end.time - shift.start.time
            for break_out in Event.objects.filter(user = shift.user, event__exact = "BEN", time__gt = shift.start.time, time__lt = shift.end.time):
               time = time - ( break_out.time - Event.objects.filter(user = break_out.user, time__lt = break_out.time, event__exact = "BST").last().time )
    return time

def __get_days_in_week(year=None, week=None):
    '''Returns when a week starts and ends.'''
    if year == None:
        year = timezone.now().year
    if week == None:
        week = timezone.now().isocalendar()[1]

    day_zero = datetime.datetime.strptime("%i %i 1"%(year, week), "%Y %W %w")
    day_zero = timezone.make_aware(day_zero)
    days = []
    for day_number in range(7):
        days.append(day_zero + datetime.timedelta(days=day_number))
    return days



@login_required
def profile(request):
    context = dict()
    if request.method == 'POST':
        event = request.POST.get('event')
        if event == 'auto_clock_out':
            auto_clock_out = request.POST.get("auto_clock_out")
            if auto_clock_out == "None":
                auto_clock_out = None
            elif auto_clock_out != None:
                try:
                    auto_clock_out = datetime.datetime.strptime(auto_clock_out,'%H:%M').time()
                except ValueError:
                    auto_clock_out = None
                    messages.error(request, "Invalid input.")

            request.user.profile.auto_clock_out = auto_clock_out
            request.user.profile.save()
        elif event == 'password':
            return_error = HttpResponseRedirect('/profile')
            password = request.POST.get('password')            
            new_password = request.POST.get('new_password')
            verified_password = request.POST.get('verified_password')
            
            __password_check(request, new_password, verified_password)
            
            if request.user.check_password(password) != True:
                messages.error(request, 'Inncorrect login password.')

            if len(messages.get_messages(request)) > 0:
                return return_error

            request.user.set_password(new_password)
            request.user.save()

            messages.info(request, 'Your password has been changed.')

    return render(request, "profile.html", context)

def register(request):
    context = dict()
    if request.user.is_authenticated == True:
        messages.error(request, 'You can\'t register while logged in.')
        return HttpResponseRedirect('/shifts')
    key = request.GET.get('key')
    if key == None:
        messages.error(request, 'Registant doesn\'t exist.')
        return HttpResponseRedirect('/')
    key = base64.urlsafe_b64decode(key)
    key_hash = hashlib.sha512(key).digest()
    registants = Registration.objects.filter(key_hash = key_hash)
    if len(registants) <= 0:
        messages.error(request, 'Registant doesn\'t exist.')
        return HttpResponseRedirect('/')
    elif len(registants) > 1:
        messages.error(request, 'Duplicate key. Something funky is going on and I am not letting you through.')
        return HttpResponseRedirect('/')
    elif request.method == 'GET':
        context['email'] = registants[0].email
        return render(request, 'registration.html', context)
    elif request.method == 'POST':
        return_error = HttpResponseRedirect('/register?key=%s'%request.GET.get('key'))
        
        username = request.POST.get('username')
        password = request.POST.get('password')
        verified_password = request.POST.get('verified_password')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        __password_check(request, password, verified_password)

        if username == None or username == '':
            messages.error(request, 'No username was supplied.')
        elif len(username) < 3:
            messages.error(request, 'Your username must be more than three characters.')
        elif len(User.objects.filter(username = username)) > 0:
            messages.error(request, 'This username is already in use.')
        
        if email == None or email == '':
            messages.error(request, 'No email was supplied.')
        else:
            email = email.lower()
            if len(User.objects.filter(email = email)) > 0:
                messages.error(request, 'This email is already in use. Invalid registration key.')
                registants[0].delete()
                return HttpResponseRedirect('/')
            elif email != registants[0].email:
                messages.error(request, 'This email doesn\'t match the key\'s email contact. Please try again.')
       
        #TODO: Make sure messages are errors
        if len(messages.get_messages(request)) > 0:
            return return_error

        try:
            User.objects.create_user(
                username = username,
                email = registants[0].email,
                password = password,

shifts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <title>{% block title %}Time{% endblock %}</title>
    </head>
    <body>
        <div class="container" role="main">
            <nav class="navbar nav-default">
                <div class="container-fluid">
                    <div class="nav-header">
                        <a class="navbar-brand" href="#">Netsville</a>
                    </div>
                    {% if user.is_authenticated %}
                        <ul class="nav nav-pills">
                            <li{% if request.path == "/shifts" %} class="active"{% endif %}><a href="/shifts">Shifts</a></li>
                            <li{% if request.path == "/export" %} class="active"{% endif %}><a href="/export">Export</a></li>
                            <li{% if request.path == "/profile" %} class="active"{% endif %}><a href="/profile">Profile</a></li>
                            {% if perms.auth.can_send_registration  %}<li{% if request.path == "/send_registration" %} class="active"{% endif %}><a href="/send_registration">Invites</a></li>{% endif %}
                            <li><a href="/logout">Logout</a></li>
                        </ul>
                    {% endif %}
                    </div>
                </nav>

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% spaceless %}
                        {% if message.level_tag == "error" %}
                            danger
                        {% else %}
                            {{ message.level_tag }}
                        {% endif %}
                    {% endspaceless %}" role="alert">
                        <a href="{{request.path}}" class="btn" role="button"><span class="glyphicon glyphicon-remove align-left" aria-hidden="true"></span></a>
                        {{ message }}    
                    </div>
                {% endfor %}
            {% endif %}

            {% block main %}
            {% endblock %}
        </div>
    </body>
</html>

shifts/templates/export.html
{% extends "base.html" %}
{% block title %}Export{% endblock %}
{% block main %}
    <div class="col-md-12">
    <h3 title="Year {{ year }} Week {{ week }}">{{ day_shifts_and_hours.0.0.date }} - {{ day_shifts_and_hours.6.0.date }}</h3>
    {% if perms.auth.can_view_others %}
        <h4>
            <div class="btn-group">
                <a class="btn btn-default" role="button" href="export?year={{ year }}&week={{ week }}&user={{user.id}}&type=csv">Download</a>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Veiwing {{view_user.username}} <span class="caret"></span>
                    <span class="sr-only">Select user</span>
                </button>
                <ul class="dropdown-menu">
                    {% for user in users %}
                        <li><a href="/export?year={{ year }}&week={{ week }}&user={{user.id}}">{{ user.username }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </h4> 
    {% endif%}
        <table class="table table-hover text-left">
            <tr>
            <th class="col-md-1">Day</th>
            <th class="col-md-1">Hours</th>
            <th class="col-md-10">Tasks</th>
            </tr>
            {% for day,shifts,hours in day_shifts_and_hours %}
                <tr>
                <td title="{{ day }}">{{ day|date:"l" }}</td>
                <td>{{ hours|floatformat:2 }}</td>
                <td>
                    {% for shift in shifts %}
                        {{ shift.tasks_completed }}
                    {% endfor %}
                </td>
                </tr>
            {% endfor %}
            <tr>
            <td>Total:</td>
            <td colspan="4">{{ total_hours|floatformat:2 }}</td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
    <ul class="nav nav-pills">
    <li><a href="{{request.path}}?year={{ last_week.0 }}&week={{ last_week.1 }}&user={{view_user.id}}"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a></li>
    <li><a href="{{request.path}}?year={{ next_week.0 }}&week={{ next_week.1 }}&user={{view_user.id}}"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></li>
    </ul>
    </div>
{% endblock %}

shifts/templates/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}
{% block main %}
<div class="col-md-6">
<form action="/login" method="POST">
{% csrf_token %}
<div class="form-group">
<label for="username">Username</label>
<input id="username" class="form-control" type="text" placeholder="User" name="username"></input>
<label for="password">Password</label>
<input id="password" class="form-control" type="password" placeholder="Password" name="password"></input>
</div>
<button class="btn btn-default" type="sumbit">Login</button>
</form>
</div>
{% endblock %}

shifts/templates/profile.html
{% extends "base.html" %}
{% block title %}
Profile
{% endblock %}
{% block main %}
    <div class="col-md-6">
        <h3>Profile for {{ request.user }}</h3>
        <div class="row">
            <h4>Auto Clock Out</h4>

            <form action="/profile" method="POST">
                {% csrf_token %}
                <label for="auto_clock_out" class="sr-only">Auto clock out</label>
                <div class="input-group">
                    <input  type="time" id="auto_clock_out" class="form-control" name="auto_clock_out" placeholder="{{ request.user.profile.auto_clock_out }}">
                    <div class="input-group-btn">
                        {% if request.user.profile.auto_clock_out != None %}
                            <button type="sumbit" class="btn btn-default" name="auto_clock_out" value="None">Disable</button>
                        {% endif %}
                        <button type="sumbit" class="btn btn-default" name="event" value="auto_clock_out">Set</button>
                    </div>
                </div>
            </form>
        </div>
           
        <div class="row"> 
            <h4>Password</h4>

            <form action="/profile" method="POST">
                {% csrf_token %}
                <div class="form-group">

                    <label for="password" class="sr-only">Current Password</label>
                    <div class="input-group">
                        <span class="input-group-addon">Current Password</span>
                        <input id="password" class="form-control" type="password" placeholder="" name="password">
                    </div>

                    <label for="password" class="sr-only">New Password</label>
                    <div class="input-group">
                        <span class="input-group-addon">New Password</span>
                        <input id="password" class="form-control" type="password" placeholder="" name="new_password">
                    </div>

                    <label for="verified_password" class="sr-only">New Password Verification</label>
                    <div class="input-group">
                        <span class="input-group-addon">New Password Again</span>
                        <input id="verified_password" class="form-control" type="password" placeholder="" name="verified_password">
                    </div>

                    <button type="sumbit" class="btn btn-default" name="event" value="password">Change Password</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

shifts/templates/registration.html
{% extends "base.html" %}
{% block title %}
Registration
{% endblock %}
{% block main %}
<div class="col-md-6">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Email</label>
                <input id="email" class="form-control" type="text" placeholder="Email" name="email" {% if email %} value="{{ email }}" readonly="true"{% endif %}></input>
            <label for="username">Username</label>
                <input id="username" class="form-control" type="text" placeholder="User" name="username"></input>
            <label for="first_name">First Name</label>
                <input id="first_name" class="form-control" type="text" placeholder="First Name" name="first_name"></input>
            <label for="last_name">Last Name</label>
                <input id="last_name" class="form-control" type="text" placeholder="Last Name" name="last_name"></input>
            <label for="password">Password</label>
                <input id="password" class="form-control" type="password" placeholder="Password" name="password"></input>
            <label for="verified_password">Password Verification</label>
                <input id="verified_password" class="form-control" type="password" placeholder="Password (again)" name="verified_password"></input>
        </div>
        <button class="btn btn-default" type="sumbit">Register</button>
    </form>
</div>
{% endblock %}

shifts/templates/sample.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block main %}
{% endblock %}

shifts/templates/send_registration.html
{% extends "base.html" %}
{% block title %}
Invites
{% endblock %}
{% block main %}
<div class="col-md-6">
    <h3>Invite</h3>
    <form id="emails" action="/send_registration" method="POST">
        <div class="form-group">
            {% csrf_token %}
            <textarea name="emails" class="form-control" cols=32 rows=15 title="Sperate emails by a line break." placeholder="Sperate emails by a line break"></textarea>
            </br>
            <button class="btn btn-default" type="sumbit">Send invitations</button>
        </div>
    </form>
</div>
<div class="col-md-6">
    <h3>Current invitations</h3>
    <ul class="list-group">
    {% for registration in registrations %}
        <li class="list-group-item">{{ registration.email }}</li>
    {% empty %}
        <li class="list-group-item">There are no invitations...</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

shifts/templates/shifts.html
{% extends "base.html" %}
{% block title %}Shifts{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-6">
            <h3>Clock</h3>
            <form action="/shifts" method="POST">
                {% csrf_token %}
                <div class="btn-group">
                    {% for choice in event_choices %}
                        <button type="sumbit" class="btn btn-default"{% if not choice.0 in possible_events %} disabled=true{% endif %} name="event" value="{{ choice.0 }}">{{ choice.1 }}</button>
                    {% endfor %}
                </div>
            </form>
                {% if last_event == None %}
                    Welcome new user!
                {% else %}
                    <ul class="list-group">
                    {% for event in lastest_events|slice:"::-1"|slice:":5" %}
                        <li class="list-group-item">{{ event.get_event_display}} @{{ event.time }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
        </div>
        <div class="col-md-6">
            <h3>Tasks</h3>
            <form action="/shifts" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    <input class="form-control" autocomplete="off" type="text" name="desc" placeholder="Task"></input>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="sumbit" {% if last_shift.out != None %}disabled{% endif %}name="event" value="task">Submit</button>
                    </span>
                </div>
            </form>
            {% if last_shift != None %}
                <ul class="list-group">
                {% for task in tasks_completed reversed %}
                    <li class="list-group-item">{{task}}</li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}